textures/de_holos/apoc
{
	qer_editorimage	textures/de_holos/apoc
	surfaceparm	nomarks
	surfaceparm	nonsolid
	surfaceparm	trans
	nopicmip
	nomipmaps
	q3map_nolightmap
	cull	twosided
	deformvertexes	autoSprite2	
    {
        map textures/de_holos/apoc_glow2
        blendFunc GL_ONE GL_ONE
        glow
        rgbGen identity
    }
}

textures/de_holos/cerb
{
	qer_editorimage	textures/de_holos/cerb
	surfaceparm	nomarks
	surfaceparm	nonsolid
	surfaceparm	trans
	nopicmip
	nomipmaps
	q3map_nolightmap
	cull	twosided
	deformvertexes	autoSprite2	
    {
        map textures/de_holos/cerb_glow
        blendFunc GL_ONE GL_ONE
        glow
        rgbGen identity
    }
}

textures/de_holos/martyr2
{
	qer_editorimage	textures/de_holos/martyr2
	surfaceparm	nomarks
	surfaceparm	nonsolid
	surfaceparm	trans
	nopicmip
	nomipmaps
	surfaceparm nolightmap
	cull	twosided
	deformvertexes	autoSprite2
  {
      map textures/de_holos/martyr_glow2
      blendFunc GL_ONE GL_ONE
      glow
      rgbGen identity
  }
}

textures/de_holos/logo
{
	qer_editorimage	textures/de_holos/logo
	surfaceparm	nomarks
	surfaceparm	nonsolid
	surfaceparm	trans
	nopicmip
	nomipmaps
	q3map_nolightmap
	cull	twosided
	deformvertexes	autoSprite2	
    {
        map textures/de_holos/logo_glow
        blendFunc GL_ONE GL_ONE
        glow
        rgbGen identity
    }
}

textures/de_holos/pandorum
{
	qer_editorimage	textures/de_holos/pandorum
	surfaceparm	nomarks
	surfaceparm	nonsolid
	surfaceparm	trans
	nopicmip
	nomipmaps
	q3map_nolightmap
	cull	twosided
	deformvertexes	autoSprite2	
    {
        map textures/de_holos/pandorum_glow
        blendFunc GL_ONE GL_ONE
        glow
        rgbGen identity
    }
}

textures/de_holos/sacrilege
{
	qer_editorimage	textures/de_holos/sacrilege
	surfaceparm	nomarks
	surfaceparm	nonsolid
	surfaceparm	trans
	nopicmip
	nomipmaps
	q3map_nolightmap
	cull	twosided
	deformvertexes	autoSprite2	
    {
        map textures/de_holos/sacrilege_glow
        blendFunc GL_ONE GL_ONE
        glow
        rgbGen identity
    }
}